# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steve Pettitt
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Made in a factory handling genetics, cancer, CRISPR, sequencing, R, ruby, rails and nuts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stveep.github.io" # the base hostname & protocol for your site
twitter_username: stveep
github_username: stveep

# Build settings
markdown: kramdown
